spring:
  application:
    name: AureliaUser
  datasource:
    url: jdbc:h2:mem:userdb
    driverClassName: org.h2.Driver
    username: sa
    password: '{cipher}d4cf8560bc7f657d6ace50d5759d0ba822dbda1296826af495a1053b5f292bb1'
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
#      dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 3002
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:3000/eureka/}
  instance:
    leaseRenewalIntervalInSeconds: 5
    prefer-ip-address: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
custom:
  salt: '{cipher}a1eea3522f6fda5796804c30c7b5bf194a48ec420e285b3da605c15094622a59'
